[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_common = { path = "../aoc_common" }
day1_1 = { path = "../day1_1" }
day1_2 = { path = "../day1_2" }
yare = "2.0.0"
